# Site settings
title: Kilojon - Jon Neale's Blog
email: your-email@domain.com
description: "Jon Neale is an awesome developer who will solve all your technical problems, amaze you with his dashing good looks and lie to you in his blog description"
baseurl: ""
url: "http://kilojon.herokuapp.com"
twitter_username: jon_neale
github_username:  joneale

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
